port 7001
bind 0.0.0.0
daemonize yes
pidfile /var/run/redis_7001.pid
dir /data/redis/7001
cluster-enabled yes
cluster-config-file nodes-7001.conf
cluster-node-timeout 5000
appendonly yes
requirepass Redis@123
masterauth Redis@123
